"use client";

import { useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type AuditRow = {
  id: string;
  table_name: string;
  entity_id: string | null;
  action: "insert" | "update" | "delete";
  actor_id: string | null;
  before_data: Record<string, unknown> | null;
  after_data: Record<string, unknown> | null;
  created_at: string;
};

const PAGE_SIZE = 25;

const BUSINESS_TABLES = [
  "accounts",
  "users",
  "reports",
  "expenses",
  "expense_ledger",
  "performance_metrics",
  "sku_mappings",
  "sku_catalog",
  "cogs",
  "pack_profiles",
  "inventory_levels",
  "inventory_movements",
  "inventory_daily_sales",
  "inventory_warehouses",
];

// Tables that are bulk-generated by report imports — hidden by default to avoid noise.
const BULK_TABLES = ["report_transactions", "report_sku_breakdowns", "report_ad_spend", "report_ad_meta", "cogs_history"];

const KEY_FIELDS: Record<string, string[]> = {
  users: ["full_name", "email", "role"],
  accounts: ["name", "currency", "vat_rate"],
  reports: ["platform", "period_start", "period_end", "net_profit", "gross_sales", "total_cogs"],
  expenses: ["description", "amount", "expense_date", "marketplace"],
  expense_ledger: ["description", "amount", "expense_date", "marketplace", "expense_type"],
  performance_metrics: ["product_name", "recorded_date", "ppc_spend", "ppc_sales", "total_sales"],
  cogs: ["sku", "unit_cost", "includes_vat", "effective_from"],
  sku_mappings: ["amazon_sku", "temu_sku_id"],
  sku_catalog: ["product_name", "temu_goods_id"],
  pack_profiles: ["name", "units_per_box", "boxes_per_pallet"],
  inventory_movements: ["sku_mapping_id", "units", "boxes", "action_type", "destination", "occurred_on"],
  inventory_daily_sales: ["sale_date", "sold_units", "returns_units", "collected_units", "platform"],
  inventory_warehouses: ["name"],
  inventory_levels: ["amazon_stock", "warehouse_stock", "recorded_on"],
};

function asScalar(value: unknown): string {
  if (value == null) return "—";
  if (typeof value === "object") return JSON.stringify(value).slice(0, 60);
  return String(value);
}

function summarizeChange(row: AuditRow): string {
  const before = (row.before_data || {}) as Record<string, unknown>;
  const after = (row.after_data || {}) as Record<string, unknown>;
  const fields = KEY_FIELDS[row.table_name] || Object.keys({ ...before, ...after }).slice(0, 4);

  if (row.action === "insert") {
    const parts = fields
      .map((field) => (after[field] != null ? `${field}=${asScalar(after[field])}` : ""))
      .filter(Boolean);
    return parts.length ? `Created with ${parts.join(", ")}` : "Created";
  }
  if (row.action === "delete") {
    const parts = fields
      .map((field) => (before[field] != null ? `${field}=${asScalar(before[field])}` : ""))
      .filter(Boolean);
    return parts.length ? `Deleted (was ${parts.join(", ")})` : "Deleted";
  }
  const changes: string[] = [];
  for (const field of fields) {
    const a = before[field];
    const b = after[field];
    if (JSON.stringify(a) !== JSON.stringify(b)) {
      changes.push(`${field}: ${asScalar(a)} → ${asScalar(b)}`);
    }
  }
  if (changes.length === 0) return "Updated (no visible field change)";
  return changes.join(" | ");
}

export default function AuditEventsPanel() {
  const [rows, setRows] = useState<AuditRow[]>([]);
  const [loading, setLoading] = useState(false);
  const [offset, setOffset] = useState(0);
  const [tableFilter, setTableFilter] = useState("business");
  const [actionFilter, setActionFilter] = useState("all");
  const [actorFilter, setActorFilter] = useState("all");
  const [dateFilter, setDateFilter] = useState("");
  const [totalCount, setTotalCount] = useState(0);
  const [actorMap, setActorMap] = useState<Record<string, string>>({});
  const [userOptions, setUserOptions] = useState<Array<{ id: string; label: string }>>([]);

  const totalPages = Math.max(1, Math.ceil(totalCount / PAGE_SIZE));
  const currentPage = Math.floor(offset / PAGE_SIZE) + 1;

  const describeEntity = (row: AuditRow) => {
    const data = row.after_data || row.before_data || {};
    if (row.table_name === "users") {
      const name = String((data as Record<string, unknown>).full_name || "");
      const email = String((data as Record<string, unknown>).email || "");
      if (name || email) return `${name}${name && email ? " | " : ""}${email}`;
    }
    if (row.table_name === "accounts") {
      const name = String((data as Record<string, unknown>).name || "");
      if (name) return name;
    }
    if (row.table_name === "reports") {
      const platform = String((data as Record<string, unknown>).platform || "");
      const start = String((data as Record<string, unknown>).period_start || "");
      const end = String((data as Record<string, unknown>).period_end || "");
      if (platform || start || end) return `${platform || "report"} ${start} to ${end}`;
    }
    if (row.table_name === "expenses" || row.table_name === "expense_ledger") {
      const description = String((data as Record<string, unknown>).description || "");
      const amount = (data as Record<string, unknown>).amount != null ? String((data as Record<string, unknown>).amount) : "";
      if (description || amount) return `${description}${amount ? ` (${amount})` : ""}`;
    }
    if (row.table_name === "performance_metrics") {
      const product = String((data as Record<string, unknown>).product_name || "");
      const date = String((data as Record<string, unknown>).recorded_date || "");
      if (product || date) return `${product}${date ? ` (${date})` : ""}`;
    }
    return row.entity_id || "-";
  };

  const loadUsers = async () => {
    const supabase = createClient();
    const { data } = await supabase.from("users").select("id, full_name, email").order("full_name", { ascending: true });
    const list = ((data || []) as Array<{ id: string; full_name: string; email: string }>).map((u) => ({
      id: String(u.id),
      label: `${u.full_name} (${u.email})`,
    }));
    setUserOptions(list);
    const map: Record<string, string> = {};
    list.forEach((u) => {
      map[u.id] = u.label;
    });
    setActorMap(map);
  };

  const loadRows = async (nextOffset = 0) => {
    setLoading(true);
    const supabase = createClient();
    let query = supabase
      .from("audit_events")
      .select("id, table_name, entity_id, action, actor_id, before_data, after_data, created_at")
      .order("created_at", { ascending: false })
      .range(nextOffset, nextOffset + PAGE_SIZE - 1);
    let countQuery = supabase.from("audit_events").select("id", { count: "exact", head: true });

    if (tableFilter === "business") {
      query = query.in("table_name", BUSINESS_TABLES);
      countQuery = countQuery.in("table_name", BUSINESS_TABLES);
    } else if (tableFilter === "bulk") {
      query = query.in("table_name", BULK_TABLES);
      countQuery = countQuery.in("table_name", BULK_TABLES);
    } else if (tableFilter !== "all") {
      query = query.eq("table_name", tableFilter);
      countQuery = countQuery.eq("table_name", tableFilter);
    }
    if (actionFilter !== "all") {
      query = query.eq("action", actionFilter);
      countQuery = countQuery.eq("action", actionFilter);
    }
    if (actorFilter !== "all") {
      query = query.eq("actor_id", actorFilter);
      countQuery = countQuery.eq("actor_id", actorFilter);
    }
    if (dateFilter) {
      query = query.gte("created_at", `${dateFilter}T00:00:00`);
      countQuery = countQuery.gte("created_at", `${dateFilter}T00:00:00`);
    }

    const [{ data }, { count }] = await Promise.all([query, countQuery]);
    const next = (data || []) as AuditRow[];
    setRows(next);
    setTotalCount(Number(count || 0));
    setLoading(false);
  };

  useEffect(() => {
    void loadUsers();
  }, []);

  useEffect(() => {
    setOffset(0);
    void loadRows(0);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [tableFilter, actionFilter, actorFilter, dateFilter]);

  const nextPage = async () => {
    const next = offset + PAGE_SIZE;
    setOffset(next);
    await loadRows(next);
  };

  const previousPage = async () => {
    const next = Math.max(0, offset - PAGE_SIZE);
    setOffset(next);
    await loadRows(next);
  };

  const tableOptions = useMemo(
    () => [
      { value: "business", label: "Business activity (default)" },
      { value: "all", label: "All tables" },
      { value: "bulk", label: "Bulk imports (report data)" },
      ...BUSINESS_TABLES.map((t) => ({ value: t, label: t })),
    ],
    []
  );

  return (
    <section className="rounded-2xl border border-slate-200 bg-white p-4">
      <div className="mb-3 flex flex-wrap items-center justify-between gap-2">
        <div>
          <h4 className="text-lg font-semibold">Audit Trail</h4>
          <p className="text-xs text-slate-500">
            Records who changed what across the portal. Defaults to high-signal business activity. Switch the table filter
            to inspect bulk imports if needed.
          </p>
        </div>
        <button
          onClick={() => void loadRows(offset)}
          className="rounded-lg bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-700"
        >
          Refresh
        </button>
      </div>

      <div className="mb-3 grid gap-2 sm:grid-cols-4">
        <select
          value={tableFilter}
          onChange={(e) => setTableFilter(e.target.value)}
          className="rounded-lg border border-slate-300 px-2 py-2 text-sm"
        >
          {tableOptions.map((opt) => (
            <option key={opt.value} value={opt.value}>
              {opt.label}
            </option>
          ))}
        </select>
        <select
          value={actionFilter}
          onChange={(e) => setActionFilter(e.target.value)}
          className="rounded-lg border border-slate-300 px-2 py-2 text-sm"
        >
          <option value="all">All actions</option>
          <option value="insert">Created</option>
          <option value="update">Updated</option>
          <option value="delete">Deleted</option>
        </select>
        <select
          value={actorFilter}
          onChange={(e) => setActorFilter(e.target.value)}
          className="rounded-lg border border-slate-300 px-2 py-2 text-sm"
        >
          <option value="all">All users</option>
          {userOptions.map((u) => (
            <option key={u.id} value={u.id}>
              {u.label}
            </option>
          ))}
        </select>
        <input
          type="date"
          value={dateFilter}
          onChange={(e) => setDateFilter(e.target.value)}
          className="rounded-lg border border-slate-300 px-2 py-2 text-sm"
        />
      </div>

      <div className="overflow-x-auto rounded-xl border border-slate-200">
        <table className="min-w-full text-sm">
          <thead className="bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500">
            <tr>
              <th className="px-3 py-2">When</th>
              <th className="px-3 py-2">User</th>
              <th className="px-3 py-2">Event</th>
              <th className="px-3 py-2">Entity</th>
              <th className="px-3 py-2">Summary of changes</th>
            </tr>
          </thead>
          <tbody>
            {loading ? (
              <tr>
                <td className="px-3 py-3 text-slate-500" colSpan={5}>
                  Loading audit events...
                </td>
              </tr>
            ) : rows.length === 0 ? (
              <tr>
                <td className="px-3 py-3 text-slate-500" colSpan={5}>
                  No audit events found.
                </td>
              </tr>
            ) : (
              rows.map((row) => (
                <tr key={row.id} className="border-t border-slate-100 align-top">
                  <td className="px-3 py-2 whitespace-nowrap">{new Date(row.created_at).toLocaleString("en-GB")}</td>
                  <td className="px-3 py-2">{row.actor_id ? actorMap[row.actor_id] || row.actor_id : "System"}</td>
                  <td className="px-3 py-2 capitalize">
                    <span
                      className={`rounded-full px-2 py-0.5 text-xs font-semibold ${
                        row.action === "insert"
                          ? "bg-emerald-100 text-emerald-700"
                          : row.action === "update"
                            ? "bg-blue-100 text-blue-700"
                            : "bg-rose-100 text-rose-700"
                      }`}
                    >
                      {row.action === "insert" ? "Created" : row.action === "update" ? "Updated" : "Deleted"}
                    </span>
                    <span className="ml-2 text-xs text-slate-500">{row.table_name}</span>
                  </td>
                  <td className="px-3 py-2">{describeEntity(row)}</td>
                  <td className="px-3 py-2 text-xs text-slate-700">{summarizeChange(row)}</td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      <div className="mt-3 flex flex-wrap items-center justify-end gap-2">
        <span className="text-xs text-slate-500">
          Page {currentPage} of {totalPages} ({totalCount} items)
        </span>
        <select
          value={currentPage}
          onChange={(e) => {
            const targetPage = Number(e.target.value);
            const next = Math.max(0, (targetPage - 1) * PAGE_SIZE);
            setOffset(next);
            void loadRows(next);
          }}
          className="rounded-lg border border-slate-300 px-2 py-1.5 text-xs"
        >
          {Array.from({ length: totalPages }, (_, i) => i + 1).map((page) => (
            <option key={page} value={page}>
              {page}
            </option>
          ))}
        </select>
        <button
          onClick={() => void previousPage()}
          disabled={offset === 0 || loading}
          className="rounded-lg bg-slate-100 px-3 py-1.5 text-xs font-semibold text-slate-700 disabled:opacity-50"
        >
          Previous
        </button>
        <button
          onClick={() => void nextPage()}
          disabled={currentPage >= totalPages || loading}
          className="rounded-lg bg-slate-100 px-3 py-1.5 text-xs font-semibold text-slate-700 disabled:opacity-50"
        >
          Next
        </button>
      </div>
    </section>
  );
}
